name: ridgePointWebPage

on:
  push:
    branches:
      - main
      - 'feature/*'
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - uses: actions/checkout@v3

      - name: Copy .env.testing.example
        run: cp .env.testing.example .env.testing

      - name: Update dependencies
        run: composer update

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Generate Application Key
        run: php artisan key:generate --env=testing

      - name: Install js dependencies
        run: npm install

      - name: Compile Vue assets
        run: npm run build

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Simbolyc link generation
        run: php artisan storage:link

      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite
        
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: vendor/bin/phpunit
